name: Update Structure Graph

permissions:
  contents: write

on:
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Generate folder structure JSON
        run: node .github/rgraph/generate-structure.js

      - name: Create HTML visualization
        run: cp .github/rgraph/structure.html .github/rgraph/output.html

      - name: Inline structure.json into output.html
        run: |
          STRUCTURE_JSON=$(cat .github/rgraph/structure.json | jq -c .)
          sed -i "s|REPLACE_ME|$STRUCTURE_JSON|" .github/rgraph/output.html

      - name: Convert HTML to image (using Puppeteer)
        run: |
          node -e "
            const puppeteer = require('puppeteer');
            (async () => {
              const delay = ms => new Promise(res => setTimeout(res, ms));
              const browser = await puppeteer.launch({
                args: ['--no-sandbox', '--disable-setuid-sandbox']
              });
              const page = await browser.newPage();
              await page.goto('file://' + process.cwd() + '/.github/rgraph/output.html', { waitUntil: 'networkidle0' });
              await delay(2000); // Wait for D3 to finish rendering
              await page.screenshot({ path: '.github/rgraph/structure.png' });
              await browser.close();
            })();
          "

      - name: Update README with image
        run: |
          sed -i '/<!-- STRUCTURE-GRAPH -->/{
          n; s|.*|![Structure](.github/rgraph/structure.png)|
          }' README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/rgraph/structure.png README.md .github/rgraph/output.html .github/rgraph/structure.json
          git commit -m "📦 Auto-update folder structure image and README" || echo "No changes to commit"
          git push origin HEAD
